[package]
name = "totp-rs"
version = "0.6.5"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
edition = "2021"
readme = "README.md"
license = "MIT"
description = "RFC-compliant TOTP implementation with ease of use as a goal and additionnal QoL features."
repository = "https://github.com/constantoine/totp-rs"
homepage = "https://github.com/constantoine/totp-rs"
keywords = ["authentication", "2fa", "totp", "hmac", "otp"]
categories = ["authentication", "web-programming"]

[package.metadata.docs.rs]
features = [ "qr", "serde_support" ]

[features]
default = []
qr = ["qrcode", "image", "base64"]
serde_support = ["serde"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
sha2 = "~0.10.1"
sha-1 = "~0.10.0"
hmac = "~0.12.0"
byteorder = "~1.4.3"
base32 = "~0.4"
qrcode = { version = "~0.12", optional = true }
image = { version = "~0.23.14", optional = true}
base64 = { version = "~0.13", optional = true }
