[package]
name = "totp-rs"
version = "0.3.1"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "This library permits the creation of 2FA authentification tokens per TOTP, the verification of said tokens, with configurable time skew, validity time of each token, algorithm and number of digits. With additional feature \"qr\", you can use it to generate a base64 png qrcode."
repository = "https://github.com/constantoine/totp-rs"
homepage = "https://github.com/constantoine/totp-rs"
keywords = ["authentification", "2fa", "totp", "hmac"]
categories = ["authentication", "web-programming"]


[features]
default = []
qr = ["qrcode", "image", "base64"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9.0"
sha-1 = "0.9.0"
hmac = "0.8.0"
byteorder = ">= 1.3"
base32 = ">= 0.4"
qrcode = { version = ">= 0.12", optional = true }
image = { version = ">= 0.23", optional = true} 
base64 = { version = ">= 0.12", optional = true }
