[package]
name = "totp-rs"
version = "0.2.5"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
description = "This library permits the creation of 2FA authentification tokens per TOTP, the verification of said tokens, with configurable time skew, validity time of each token, algorithm and number of digits."
repository = "https://github.com/constantoine/totp-rs"
homepage = "https://github.com/constantoine/totp-rs"
keywords = ["authentification", "2fa", "totp", "hmac"]
categories = ["authentication", "web-programming"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
ring = ">= 0.13"
byteorder = ">= 1.3"
base32 = ">= 0.4"
qrcode = ">= 0.12"
image = ">= 0.23"
base64 = ">= 0.12"
