[package]
name = "totp-rs"
version = "5.0.1"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
rust-version = "1.61"
edition = "2021"
readme = "README.md"
license = "MIT"
description = "RFC-compliant TOTP implementation with ease of use as a goal and additionnal QoL features."
repository = "https://github.com/constantoine/totp-rs"
homepage = "https://github.com/constantoine/totp-rs"
keywords = ["authentication", "2fa", "totp", "hmac", "otp"]
categories = ["authentication", "web-programming"]

[package.metadata.docs.rs]
features = [ "qr", "serde_support", "gen_secret" ]

[features]
default = []
otpauth = ["url", "urlencoding"]
qr = ["qrcodegen", "image", "base64", "otpauth"]
serde_support = ["serde"]
gen_secret = ["rand"]
steam = []

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
sha2 = "0.10"
sha1 = "0.10"
hmac = "0.12"
base32 = "0.4"
urlencoding = { version = "2.1", optional = true}
url = { version = "2.3", optional = true }
constant_time_eq = "0.2"
qrcodegen = { version = "1.8", optional = true }
image = { version = "0.24", features = ["png"], optional = true, default-features = false}
base64 = { version = "0.21", optional = true }
rand = { version = "0.8", features = ["std_rng", "std"], optional = true, default-features = false }
zeroize = { version = "1.6", features = ["alloc", "derive"], optional = true }