[package]
name = "totp"
version = "0.2.0"
authors = ["Cleo Rebert <cleo.rebert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.16.12"
byteorder = "1.3.4"
otpauth = "0.4.1"
base32 = "0.4.0"
qrcode = "0.12.0"
image = "0.23.3"
base64 = "0.12.0"
